name: Function App Build
description: 'build azure function code'   

  
inputs:
  environment_name: 
    description: 'name of the azure environment'
    required: true
    default: 'dev01'
    
  azure_tenant_id:  
    description: 'azure subscription id '
    required: true
  azure_subscription_id:
    description: 'azure subscription id '
    required: true
  client_id:  
    description: 'service principal client id '
    required: true
  client_secret: 
    description: 'service principal client id '
    required: true
  resource_group_name: 
    description: 'resource_group_name '
    required: true
  function_app_name: 
    description: 'function_app_name '
    required: true
  LOCATION_ABBREVIATION:  # path
    description: 'location'
    required: true
    default: 'uks'
  source_directory:  # path
    description: 'source code directory'
    required: true
    default: './'
  DOTNET_VERSION:  # path
    description: 'version of dotnet'
    required: true
    default: '6.0'

runs:
  using: "composite"
  steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@master

      - name: Login via Az module
        id: login
        uses: azure/login@v1
        with:
          creds: '{"clientId":"${{ inputs.client_id }}","clientSecret":"${{ inputs.client_secret }}","subscriptionId":"${{ inputs.azure_subscription_id }}","tenantId":"${{ inputs.azure_tenant_id }}"}'
          enable-AzPSSession: true

      - name: Get Publishing Profile
        id: getpublishingprofile
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $profile = Get-AzWebAppPublishingProfile `
                -ResourceGroupName ${{ inputs.resource_group_name }} `
                -Name ${{ inputs.function_app_name }} 
            $profile = $profile.Replace("`r", "").Replace("`n", "")
            Write-Output "::set-output name=profile::$profile"
          azPSVersion: latest

      - name: Setup DotNet ${{ inputs.DOTNET_VERSION }} Environment
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ inputs.DOTNET_VERSION }}

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ${{inputs.source_directory}}

      - name: dotnet publish
          run: dotnet publish -c Release -o ${{inputs.source_directory}}/drop
          working-directory: ${{inputs.source_directory}}

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: function-app
          path: ${{inputs.source_directory}}/drop
