# This is an example of using Composite Run Steps Actions

name: function-app-deployment

env:
  ROOT_PATH: './azure-function/azure-function'     
  DOTNET_VERSION: '6.x.x'
  LOCATION_ABBREVIATION: 'demo'
  ENV_SUFFIX: '001'
  
  
on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    inputs: 
      ENVIRONMENT_NAME:
        description: 'Environment Name'
        type: string
        required: true
        default: 'dev01'
    secrets:
      AZURE_AD_CLIENT_ID: 
        required: true

  
jobs:
  build:
    runs-on: ubuntu-latest
    name: function app build
    
    steps:
    - uses: actions/checkout@v2
    
    - id: function_app_build
      uses: ./function-app/build
      with:
        source_directory: ${{ env.ROOT_PATH }}
        DOTNET_VERSION:  ${{ env.DOTNET_VERSION }}
   
  deploy_dev:
    name: DEPLOY_DEV
    runs-on: ubuntu-latest
    needs: [build]
    environment:
      name: ${{ inputs.ENVIRONMENT_NAME }}
      #url: ${{ steps.functionsaction.outputs.webapp-url }}

    steps:
      - uses: actions/checkout@v2
      
      - id: function_app_deploy
        uses: ./function-app/deploy
        with:
          azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
          azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client_id: ${{ secrets[format('AZURE_CLIENT_ID_{0}', inputs.ENVIRONMENT_NAME )] }}
          client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
          resource_group_name: 'demo-rg'
          function_app_name: 'function-${{ env.LOCATION_ABBREVIATION }}-${{ env.ENV_SUFFIX }}'
          source_directory: ${{ env.ROOT_PATH }}
          
