# This is an example of using Composite Run Steps Actions

name: function-app-deployment

env:
  ROOT_PATH: './azure-function/azure-function'     
  DOTNET_VERSION: '6.0.x'

on:
  push:
    branches:
      - main
  workflow_dispatch:
  workflow_call:
    inputs: 
      ENVIRONMENT_NAME:
        description: 'Environment Name'
        type: string
        required: true
        default: 'dev01'
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: function app devploy
    
    steps:
    - uses: actions/checkout@v2
    
    - id: function_app_build
      uses: krishrocks1904/azure-function-deplo-99/function-app/deployment@fv14
      with:
        environment_name: ${{ inputs.ENVIRONMENT_NAME }}
        source_directory: ${{ env.ROOT_PATH }}
        dotnet_version:  ${{ env.DOTNET_VERSION }}
        azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        azure_subscription_id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        client_id:  ${{ secrets.AZURE_CLIENT_ID }}
        client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        function_resource_group_name: 'demo-rg'
        function_app_name: 'function-demo-001'
        
   
          
