# This is an example of using Composite Run Steps Actions

name: Composite Example

on: [workflow_dispatch]

jobs:
  function_app_build:
    runs-on: ubuntu-latest
    name: function app build
    steps:
    - uses: actions/checkout@v2
    - id: function_app_build
      uses: krishrocks1904/azure-function-deplo-99@v1 
      with:
        environment_name: 'dev01'
        azure_tenant_id: 'azure subscription id '
        azure_subscription_id: 'azure subscription id '
        client_id:  'service principal client id '
        client_secret: 'service principal client id '
        resource_group_name: 'resource_group_name '
        function_app_name: 'function_app_name '
        LOCATION_ABBREVIATION: 'uks'
        source_directory: './'
        DOTNET_VERSION:  '6.0'
   
