# This is an example of using Composite Run Steps Actions

name: function-app-deployment

on: [workflow_dispatch]

jobs:
  function_app_build:
    runs-on: ubuntu-latest
    name: function app build
    steps:
    - uses: actions/checkout@v2
    - id: function_app_build
      uses: krishrocks1904/azure-function-deplo-99@main
      with:
        environment_name: 'dev01'
        azure_tenant_id: ${{ secrets.AZURE_TENANT_ID }}
        azure_subscription_id: ${{ secrets.AZURE_TENANT_ID }}
        client_id:  ${{ secrets.AZURE_CLIENT_ID }}
        client_secret: ${{ secrets.AZURE_CLIENT_SECRET }}
        resource_group_name: 'demo-rg'
        function_app_name: 'function-demo-001'
        LOCATION_ABBREVIATION: 'uks'
        source_directory: './'
        DOTNET_VERSION:  '6.0'
   
